### ISSUE TITLE
Implement standard project workflow and testing

### ISSUE THREAD

**Issue by hpdang** [fossasia/pslab#10]
In order to welcome more devs, we need to implement a standard workflow. Please:
* [ ] Set up a development branch and merge the dev branch once a week to master
* [ ] Add test frameworks (Which ones are suitable? travis, codecov, gemnasium, codeclimate..)

**Comment by wavicles** [comment]
@hpdang  Thanks for the help and guidance with standard work-flow and testing frameworks. 
I have added Travis CI test framework and the builds are passed. 
[](https://travis-ci.org/fossasia/pslab)

**Comment by wavicles** [comment]
@hpdang  I have also created development branch for both the repos pslab and pslab-apps
