### ISSUE TITLE
add steps in readme to generate documentation and complete PSL.SENSORS.rst file

### ISSUE THREAD

**Issue by viveksb007** [fossasia/pslab#36]
Add steps in readme to generate documentation. And modify PSL.SENSORS.rst to produce documentation of SENSORS subpackage also.

**Currently** : Sensors documentation is not generated & steps to produce documentation is not mentioned in readme.

**I would like to send a PR to solve this.**

**Comment by wavicles** [comment]
@viveksb007 Please go ahead and send the PR.
